{% set name = "roary" %}
{% set version = "3.12.0" %}
{% set hash = "ce55cb605b792c601577e9aaea3b84d4813e4f32e6661827858e9dce936eb963" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 1

source:
  url: http://search.cpan.org/CPAN/authors/id/A/AJ/AJPAGE/Bio-Roary-{{ version }}.tar.gz
  sha256: {{ hash }}

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl =5.26
    - perl-app-cpanminus
    - perl-module-build
    - perl-bioperl
    - perl-bioperl-core
    - perl-array-utils
    - perl-text-csv
    - perl-moose
    - perl-exception-class
    - perl-file-grep
    - perl-file-find-rule
    - perl-log-log4perl
    - perl-file-slurper
    - perl-file-find-rule
    - perl-graph-readwrite
    - perl-env-path
    - perl-perlio-utf8_strict
    - mcl =14.137
    - bedtools =2.27.1
    - prank
    - mafft
    - cd-hit =4.6.8
    - blast =2.6.0
    - parallel
    - fasttree =2.1.9
    - perl-test-output
    - perl-test-most
    - perl-test-files
    - perl-digest-md5-file

  run:
    - perl =5.26
    - perl-bioperl
    - perl-bioperl-core
    - perl-array-utils
    - perl-text-csv
    - perl-moose
    - perl-exception-class
    - perl-file-grep
    - perl-file-find-rule
    - perl-log-log4perl
    - perl-file-slurper
    - perl-file-find-rule
    - perl-graph-readwrite
    - perl-env-path
    - perl-perlio-utf8_strict
    - mcl =14.137
    - bedtools =2.27.1
    - prank
    - mafft
    - cd-hit =4.6.8
    - blast =2.6.0
    - parallel
    - fasttree =2.1.9
    - perl-test-output
    - perl-test-most
    - perl-test-files
    - perl-digest-md5-file

test:
  commands:
    #Test if the help loads correctly
    - roary -h 2>&1 | grep Usage
    - query_pan_genome -h 2>&1 | grep Usage

about:
  home: https://github.com/sanger-pathogens/Roary
  license: GPL-3.0
  license_file: GPL-LICENSE
  summary: 'Rapid large-scale prokaryote pan genome analysis'
